// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2P_UhW9hMJyEqaiEU0pl9QEnqYoANgA',
    appId: '1:450973185671:web:99c2d14b095c12e5d4aa22',
    messagingSenderId: '450973185671',
    projectId: 'fir-demo-ff04d',
    authDomain: 'fir-demo-ff04d.firebaseapp.com',
    storageBucket: 'fir-demo-ff04d.appspot.com',
    measurementId: 'G-ZYQBEYEYBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBabEglWb5F7gAwWz6tGmwjLz3kjsQO9s8',
    appId: '1:450973185671:android:a85c64564ab5b3fdd4aa22',
    messagingSenderId: '450973185671',
    projectId: 'fir-demo-ff04d',
    storageBucket: 'fir-demo-ff04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs08x0FzefZx0aUSNB9gHgQigNsuN9hn8',
    appId: '1:450973185671:ios:d9cd8a820d010661d4aa22',
    messagingSenderId: '450973185671',
    projectId: 'fir-demo-ff04d',
    storageBucket: 'fir-demo-ff04d.appspot.com',
    iosClientId: '450973185671-h7dbh942ke7cvgol8drn176h3vc7jc8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs08x0FzefZx0aUSNB9gHgQigNsuN9hn8',
    appId: '1:450973185671:ios:d9cd8a820d010661d4aa22',
    messagingSenderId: '450973185671',
    projectId: 'fir-demo-ff04d',
    storageBucket: 'fir-demo-ff04d.appspot.com',
    iosClientId: '450973185671-h7dbh942ke7cvgol8drn176h3vc7jc8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
